name: Generate Snake

on:
  schedule:
    # Berjalan setiap 6 jam
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Periksa kode
        uses: actions/checkout@v2

      - name: Hasilkan Animasi Ular
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: HarlanGilbran
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit dan Push Perubahan
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/
          git diff --quiet && git diff --staged --quiet || git commit -m "Perbarui kontribusi ular"
          git push origin main || { echo "Gagal melakukan push perubahan"; exit 1; }
